name: Schedule Leaderboard Update

on:
  schedule:
    # Runs at 18:15 UTC (11:45 PM IST) every day
    - cron: '15 18 * * *'

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Update Leaderboard
        run: |
          curl -X POST https://pointblank.club/api/hustle