name: Schedule Leaderboard Update

on:
  schedule:
    # Runs at 18:35 UTC (11:55 PM IST) every day
    - cron: "55 18 * * *"
  # Manual trigger option
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: false
        default: "Manual testing"

permissions:
  contents: read

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Check current time
        run: |
          echo "Current time: $(date)"
          echo "Current UTC time: $(date -u)"

      - name: Update Leaderboard
        id: update
        run: |
          echo "Sending request to update leaderboard..."

          # Adding browser-like User-Agent and additional headers to avoid anti-bot detection
          USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

          # Try up to 3 times with 10 second delay between attempts
          for i in {1..3}; do
            echo "Attempt $i of 3..."
            
            response=$(curl -L -X POST "https://www.pointblank.club/api/hustle" \
              -H "User-Agent: $USER_AGENT" \
              -H "Accept: application/json, text/plain, */*" \
              -H "Accept-Language: en-US,en;q=0.9" \
              -H "Content-Type: application/json" \
              -H "Origin: https://www.pointblank.club" \
              -H "Referer: https://www.pointblank.club/" \
              -w "\n%{http_code}" -o response.txt \
              --compressed)
            
            status_code=$(echo "$response" | tail -n1)
            echo "Response status code: $status_code"
            
            if [[ $status_code == 2* ]]; then
              echo "Leaderboard update triggered successfully"
              cat response.txt
              exit 0
            else
              echo "Attempt $i failed with status code: $status_code"
              cat response.txt
              # Sleep before retrying, except on last attempt
              if [ $i -lt 3 ]; then
                echo "Waiting 10 seconds before next attempt..."
                sleep 10
              fi
            fi
          done

          echo "All attempts failed to update leaderboard"
          exit 1

      - name: Send notification on failure
        if: failure() && github.event_name == 'schedule'
        run: |
          echo "Leaderboard update failed. Please check the GitHub Actions logs for details."
