name: Update Leaderboard Every Friday

on:
  schedule:
    - cron: "0 19 * * 5"

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger API to Update Leaderboard
        run: |
          curl -X POST "https://pointblank.club/api/hustle" || echo "API call failed"
