name: Schedule Leaderboard Update

on:
  schedule:
    # Runs at 18:25 UTC (11:55 PM IST) every day
    - cron: "25 18 * * *"

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Update Leaderboard
        run: |
          curl -X POST https://pointblank.club/api/hustle
